modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="${mod_license}"

[[mods]] #mandatory
modId="tutorialmod" #mandatory
version="1.0.0" #mandatory
displayName="TutorialMod" #mandatory
authors="sironeko0295" #optional
description='''TutorialMod create by sironeko'''

[[dependencies.tutorialmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.tutorialmod]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"